FROM alpine:latest
RUN apk update && apk add nginx && apk add php

#RUN mkdir -p /usr/src/app/
#WORKDIR /usr/src/app/
COPY ./nginx.conf /etc/nginx/nginx.conf
COPY ./index.php /usr/share/nginx/html/index.php



CMD ["/usr/sbin/nginx","-g","daemon off;"]

EXPOSE 80
