version: '3.5'
services:
  web_app:
    build: .
    ports:
      - "80:8080"
    depends_on:
      - db
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_PASSWORD: my_password
      MYSQL_USER: my_user
    expose:
      - 3306
